### PR TITLE
Update Windows project

### PR DESCRIPTION
**Pull request by kuleshov-aleksei**
Just a bit changes in ToolsVersion (MSVS project)

### CODE REVIEW

**Comment by alfredh** [comment]
does it build without warnings ?

could you paste the build log here ?

**Comment by kuleshov-aleksei** [comment]
1>[Building re-win32 here]

**Debug configuration:**
2>------ Rebuild All started: Project: rem-win32, Configuration: Debug Win32 ------
2>  aubuf.c
2>  auconv.c
2>  aufile.c
2>  wave.c
2>  resamp.c
2>  tone.c
2>  fmt.c
2>  fir.c
2>  g711.c
2>  vconv.c
2>  draw.c
2>  fmt.c
2>  frame.c
2>  rem.vcxproj -> C:\baresip\rem\mk\win32\..\..\Win32\Debug\bin\rem-win32.lib
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Release configuration:**
2>------ Rebuild All started: Project: rem-win32, Configuration: Release Win32 ------
2>  aubuf.c
2>  auconv.c
2>  aufile.c
2>  wave.c
2>  resamp.c
2>  tone.c
2>  fmt.c
2>  fir.c
2>  g711.c
2>  vconv.c
2>  draw.c
2>  fmt.c
2>  frame.c
2>  rem.vcxproj -> C:\baresip\rem\mk\win32\..\..\Win32\Release\bin\rem-win32.lib
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Comment by alfredh** [comment]
I think the new modules `dtmf` and `goertzel` are missing from the Win32 project files:

```
src/goertzel/goertzel.c
src/dtmf/dec.c
```

could you please also add them to the MSVC project files ?

Alfred

**Comment by kuleshov-aleksei** [comment]
Thank you for noticing this. I've added this files to project

**Comment by alfredh** [comment]
this looks fine to me now.

@richaas should we merge to master ?

**Comment by alfredh** [comment]
hi @Encamy 

Many thanks for your contributions :)

Do you think you can also add Visual Studio project files to retest:

https://github.com/creytiv/retest

Retest is a test program for libre and librem, and it would be quite
interesting to see if it compiles and runs on Windows (with windows compiler).


Thanks,

Alfred

**Comment by kuleshov-aleksei** [comment]
Hello, @alfredh 
I'm sorry, but I can't make MSVS project
As I understand, retest is using openssl. Adding it to windows build is hard task. Maybe later I can handle with this objective.

**Pull request merged**
